name: GitHub Actions Check Compile
run-name: Checking Maven Build Status
on: [pull_request]

jobs:
  Check-Maven-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            distribution: 'adopt'
            java-version: '17'


      - name: Install maven
        run: sudo apt-get install maven

      - name: Check maven
        run: mvn -version

      - name: Maven compile
        run: |
          cd $GITHUB_WORKSPACE  # Ensure you are in the correct directory
          mvn compile

#      - name: Package the project
#        run: cd ../..; mvn package

      - name: Run maven test
        run: mvn test

#      - name: Clean maven project
#        run: cd ../..; mvn clean